### ISSUE TITLE
Creds File

### ISSUE THREAD

**Issue by oliverfriedmann** [foodji/mongo-service-profiler#5]
there should additionally be the possibility of a file `~/.mongostat/creds.yaml`
which by default should be read if existing
and the entries in there should be of the form

```
profile1:
  url: ...
  db: ...
  collection: ...
profile2:
  url: ...
  db: ...
  collection: ...
```
and then you can run `mongostat --profile profile1 …`
this is great for handling multiple different dbs regularly
(inspired by the way the aws cli handles different aws accounts)
